#!/usr/bin/python3

import amulet
import requests
import unittest


class TestCharm(unittest.TestCase):
    def setUp(self):
        self.d = amulet.Deployment()

        self.d.add('quagga')
        self.d.expose('quagga')

        self.d.setup(timeout=900)
        self.d.sentry.wait()

        self.unit = self.d.sentry['quagga'][0]

    def test_service(self):
        # noop
        pass
        
if __name__ == '__main__':
    unittest.main()
